name: Build


on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: translationtool.phar

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up php 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          coverage: none

      - name: Build translationtool.phar
        working-directory: translations/translationtool/
        run: make translationtool.phar

      - name: Check build changes
        run: |
          git status --porcelain translations/translationtool/
          bash -c "[[ ! \"`git status --porcelain translations/translationtool/translationtool.phar`\" ]] || exit 1"
